In [1]:
import numpy as np

In [6]:
a = np.array([[1,3],[-2,4]])
b = np.array([[3,-2],[5,6]])

In [10]:
np.dot(a,b)

array([[18, 16],
       [14, 28]])

In [11]:
np.dot(b,a)

array([[ 7,  1],
       [-7, 39]])

In [12]:
np.linalg.inv(a)

array([[ 0.4, -0.3],
       [ 0.2,  0.1]])